# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BusquedaPersonalizada.ui'
#
# Created: Tue Dec 09 09:38:42 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BusquedaPersonalizada(object):
    def setupUi(self, BusquedaPersonalizada):
        BusquedaPersonalizada.setObjectName(_fromUtf8("BusquedaPersonalizada"))
        BusquedaPersonalizada.resize(1248, 596)
        BusquedaPersonalizada.setMinimumSize(QtCore.QSize(1248, 596))
        BusquedaPersonalizada.setMaximumSize(QtCore.QSize(1248, 596))
        BusquedaPersonalizada.setAcceptDrops(False)
        self.centralwidget = QtGui.QWidget(BusquedaPersonalizada)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 520, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 1221, 161))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.TxtCodeAnimal = QtGui.QLineEdit(self.groupBox)
        self.TxtCodeAnimal.setEnabled(False)
        self.TxtCodeAnimal.setGeometry(QtCore.QRect(210, 40, 113, 20))
        self.TxtCodeAnimal.setObjectName(_fromUtf8("TxtCodeAnimal"))
        self.BotonBusqueda = QtGui.QPushButton(self.groupBox)
        self.BotonBusqueda.setEnabled(False)
        self.BotonBusqueda.setGeometry(QtCore.QRect(1130, 130, 75, 23))
        self.BotonBusqueda.setObjectName(_fromUtf8("BotonBusqueda"))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 40, 16, 17))
        self.radioButton.setText(_fromUtf8(""))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 110, 16, 17))
        self.radioButton_2.setText(_fromUtf8(""))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 141, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.TxtnomAnimal = QtGui.QLineEdit(self.groupBox)
        self.TxtnomAnimal.setEnabled(False)
        self.TxtnomAnimal.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.TxtnomAnimal.setObjectName(_fromUtf8("TxtnomAnimal"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(265, 110, 101, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.TxtEnvergadura = QtGui.QLineEdit(self.groupBox)
        self.TxtEnvergadura.setEnabled(False)
        self.TxtEnvergadura.setGeometry(QtCore.QRect(380, 110, 113, 20))
        self.TxtEnvergadura.setObjectName(_fromUtf8("TxtEnvergadura"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(740, 20, 331, 81))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 771, 51))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 1221, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(220, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.L1 = QtGui.QLabel(self.groupBox_2)
        self.L1.setGeometry(QtCore.QRect(80, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L1.setFont(font)
        self.L1.setObjectName(_fromUtf8("L1"))
        self.L2 = QtGui.QLabel(self.groupBox_2)
        self.L2.setGeometry(QtCore.QRect(300, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L2.setFont(font)
        self.L2.setObjectName(_fromUtf8("L2"))
        self.L3 = QtGui.QLabel(self.groupBox_2)
        self.L3.setGeometry(QtCore.QRect(600, 30, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L3.setFont(font)
        self.L3.setObjectName(_fromUtf8("L3"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(510, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.L4 = QtGui.QLabel(self.groupBox_2)
        self.L4.setGeometry(QtCore.QRect(90, 70, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L4.setFont(font)
        self.L4.setObjectName(_fromUtf8("L4"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(310, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.L5 = QtGui.QLabel(self.groupBox_2)
        self.L5.setGeometry(QtCore.QRect(420, 70, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L5.setFont(font)
        self.L5.setObjectName(_fromUtf8("L5"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(590, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.L6 = QtGui.QLabel(self.groupBox_2)
        self.L6.setGeometry(QtCore.QRect(690, 70, 511, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L6.setFont(font)
        self.L6.setObjectName(_fromUtf8("L6"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(20, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.L7 = QtGui.QLabel(self.groupBox_2)
        self.L7.setGeometry(QtCore.QRect(90, 110, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L7.setFont(font)
        self.L7.setObjectName(_fromUtf8("L7"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(270, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.L8 = QtGui.QLabel(self.groupBox_2)
        self.L8.setGeometry(QtCore.QRect(380, 110, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L8.setFont(font)
        self.L8.setObjectName(_fromUtf8("L8"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(20, 150, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.L10 = QtGui.QLabel(self.groupBox_2)
        self.L10.setGeometry(QtCore.QRect(80, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L10.setFont(font)
        self.L10.setObjectName(_fromUtf8("L10"))
        self.L9 = QtGui.QLabel(self.groupBox_2)
        self.L9.setGeometry(QtCore.QRect(790, 110, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L9.setFont(font)
        self.L9.setObjectName(_fromUtf8("L9"))
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(630, 110, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.L11 = QtGui.QLabel(self.groupBox_2)
        self.L11.setGeometry(QtCore.QRect(270, 150, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L11.setFont(font)
        self.L11.setObjectName(_fromUtf8("L11"))
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(210, 150, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(460, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.L12 = QtGui.QLabel(self.groupBox_2)
        self.L12.setGeometry(QtCore.QRect(550, 150, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L12.setFont(font)
        self.L12.setObjectName(_fromUtf8("L12"))
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(20, 190, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(780, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.L13 = QtGui.QLabel(self.groupBox_2)
        self.L13.setGeometry(QtCore.QRect(890, 150, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L13.setFont(font)
        self.L13.setObjectName(_fromUtf8("L13"))
        self.L14 = QtGui.QLabel(self.groupBox_2)
        self.L14.setGeometry(QtCore.QRect(80, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L14.setFont(font)
        self.L14.setObjectName(_fromUtf8("L14"))
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(210, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.L15 = QtGui.QLabel(self.groupBox_2)
        self.L15.setGeometry(QtCore.QRect(330, 190, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L15.setFont(font)
        self.L15.setObjectName(_fromUtf8("L15"))
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(20, 230, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(540, 190, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(1020, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.L16 = QtGui.QLabel(self.groupBox_2)
        self.L16.setGeometry(QtCore.QRect(740, 190, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L16.setFont(font)
        self.L16.setObjectName(_fromUtf8("L16"))
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(430, 230, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.L17 = QtGui.QLabel(self.groupBox_2)
        self.L17.setGeometry(QtCore.QRect(1110, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L17.setFont(font)
        self.L17.setObjectName(_fromUtf8("L17"))
        self.L18 = QtGui.QLabel(self.groupBox_2)
        self.L18.setGeometry(QtCore.QRect(180, 230, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L18.setFont(font)
        self.L18.setObjectName(_fromUtf8("L18"))
        self.L19 = QtGui.QLabel(self.groupBox_2)
        self.L19.setGeometry(QtCore.QRect(500, 230, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L19.setFont(font)
        self.L19.setObjectName(_fromUtf8("L19"))
        self.L20 = QtGui.QLabel(self.groupBox_2)
        self.L20.setGeometry(QtCore.QRect(970, 230, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L20.setFont(font)
        self.L20.setObjectName(_fromUtf8("L20"))
        self.label_44 = QtGui.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(850, 230, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(20, 270, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.L21 = QtGui.QLabel(self.groupBox_2)
        self.L21.setGeometry(QtCore.QRect(120, 270, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L21.setFont(font)
        self.L21.setObjectName(_fromUtf8("L21"))
        self.label_47 = QtGui.QLabel(self.groupBox_2)
        self.label_47.setGeometry(QtCore.QRect(560, 270, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.L22 = QtGui.QLabel(self.groupBox_2)
        self.L22.setGeometry(QtCore.QRect(680, 270, 491, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L22.setFont(font)
        self.L22.setObjectName(_fromUtf8("L22"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1070, 530, 161, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        BusquedaPersonalizada.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(BusquedaPersonalizada)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BusquedaPersonalizada.setStatusBar(self.statusbar)

        self.retranslateUi(BusquedaPersonalizada)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BusquedaPersonalizada.Volver)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BusquedaPersonalizada.HabilitarUno)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), BusquedaPersonalizada.HabilitarVarios)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.TxtCodeAnimal.clear)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.TxtEnvergadura.clear)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.TxtnomAnimal.clear)
        QtCore.QObject.connect(self.BotonBusqueda, QtCore.SIGNAL(_fromUtf8("clicked()")), BusquedaPersonalizada.Buscar)
        QtCore.QMetaObject.connectSlotsByName(BusquedaPersonalizada)

    def retranslateUi(self, BusquedaPersonalizada):
        BusquedaPersonalizada.setWindowTitle(_translate("BusquedaPersonalizada", "Busqueda Personalizada", None))
        self.pushButton.setText(_translate("BusquedaPersonalizada", "Volver", None))
        self.groupBox.setTitle(_translate("BusquedaPersonalizada", "Buscar por", None))
        self.BotonBusqueda.setText(_translate("BusquedaPersonalizada", "Buscar", None))
        self.label_2.setText(_translate("BusquedaPersonalizada", "Codigo del animal", None))
        self.label_3.setText(_translate("BusquedaPersonalizada", "Nombre", None))
        self.label_5.setText(_translate("BusquedaPersonalizada", "Envergadura", None))
        self.label_7.setText(_translate("BusquedaPersonalizada", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt;\">Tenga en cuenta que solo debe ingresar </span></p><p align=\"justify\"><span style=\" font-size:10pt;\">el numero del codigo sin el indicativo Ejem. </span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Si el codigo es MHNU-O-9 solo debe ingresar el 9</span></p></body></html>", None))
        self.label.setText(_translate("BusquedaPersonalizada", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#0000ff;\">Busqueda Especifica</span></p></body></html>", None))
        self.groupBox_2.setTitle(_translate("BusquedaPersonalizada", "Resultados", None))
        self.label_8.setText(_translate("BusquedaPersonalizada", "Codigo", None))
        self.label_9.setText(_translate("BusquedaPersonalizada", "Nombre", None))
        self.L1.setText(_translate("BusquedaPersonalizada", "--", None))
        self.L2.setText(_translate("BusquedaPersonalizada", "--", None))
        self.L3.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_13.setText(_translate("BusquedaPersonalizada", "Taxonomia", None))
        self.label_14.setText(_translate("BusquedaPersonalizada", "Latitud", None))
        self.L4.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_16.setText(_translate("BusquedaPersonalizada", "Longitud", None))
        self.L5.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_18.setText(_translate("BusquedaPersonalizada", "Localizacion", None))
        self.L6.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_20.setText(_translate("BusquedaPersonalizada", "Estado", None))
        self.L7.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_22.setText(_translate("BusquedaPersonalizada", "Metodo", None))
        self.L8.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_24.setText(_translate("BusquedaPersonalizada", "Sexo", None))
        self.L10.setText(_translate("BusquedaPersonalizada", "--", None))
        self.L9.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_27.setText(_translate("BusquedaPersonalizada", "Fecha Ingreso", None))
        self.L11.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_28.setText(_translate("BusquedaPersonalizada", "Peso", None))
        self.label_29.setText(_translate("BusquedaPersonalizada", "Habitat", None))
        self.L12.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_31.setText(_translate("BusquedaPersonalizada", "Edad", None))
        self.label_32.setText(_translate("BusquedaPersonalizada", "Anotaciones", None))
        self.L13.setText(_translate("BusquedaPersonalizada", "--", None))
        self.L14.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_35.setText(_translate("BusquedaPersonalizada", "Envergadura", None))
        self.L15.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_37.setText(_translate("BusquedaPersonalizada", "Contenido Estomacal", None))
        self.label_38.setText(_translate("BusquedaPersonalizada", "Informacion Reproductiva", None))
        self.label_39.setText(_translate("BusquedaPersonalizada", "Grasa(Kg)", None))
        self.L16.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_40.setText(_translate("BusquedaPersonalizada", "Muda", None))
        self.L17.setText(_translate("BusquedaPersonalizada", "--", None))
        self.L18.setText(_translate("BusquedaPersonalizada", "--", None))
        self.L19.setText(_translate("BusquedaPersonalizada", "--", None))
        self.L20.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_44.setText(_translate("BusquedaPersonalizada", "Partes Blandas", None))
        self.label_45.setText(_translate("BusquedaPersonalizada", "Gonodas", None))
        self.L21.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_47.setText(_translate("BusquedaPersonalizada", "Oscificacion", None))
        self.L22.setText(_translate("BusquedaPersonalizada", "--", None))
        self.label_6.setText(_translate("BusquedaPersonalizada", "Universidad de los Llanos 2014 ®", None))

